CREATE TABLE IF NOT EXISTS sdopang1_ipcrf (
    ipcrf_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    school_year VARCHAR(50) NOT NULL,
    rating_period VARCHAR(50) NOT NULL,
    date_prepared DATE DEFAULT NULL,
    employee_targets TEXT DEFAULT NULL,
    employee_accomplishments TEXT DEFAULT NULL,
    employee_indicators TEXT DEFAULT NULL,
    status ENUM('Draft','For Review','Reviewed','Approved','Returned') DEFAULT 'For Review',
    overall_rating DECIMAL(5,2) DEFAULT NULL,
    remarks TEXT DEFAULT NULL,
    reviewed_by INT DEFAULT NULL,
    approved_by INT DEFAULT NULL,
    date_reviewed DATE DEFAULT NULL,
    date_approved DATE DEFAULT NULL,
    uploaded_pdf VARCHAR(255) DEFAULT NULL,
    uploaded_excel VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ipcrf_user (user_id),
    INDEX idx_ipcrf_status (status),
    INDEX idx_ipcrf_period (school_year, rating_period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
